# **************************************************************************
# *
# * Authors:     Daniel Del Hoyo (ddelhoyo@cnb.csic.es)
# *
# * Unidad de  Bioinformatica of Centro Nacional de Biotecnologia , CSIC
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************

import os

from pyworkflow.protocol import params

from pwem.protocols import EMProtocol

from autodock import Plugin as autodockPlugin
from autodock.objects import RingtailDatabase

inputOptions = ['AutoDock-GPU', 'Vina']

class ProtRingtailCreation(EMProtocol):
  """Create a Ringtail database with the results of a docking experiment with AutoDock-GPU or Vina
  
  User IA Manual: RingtailCreate Protocol

The RingtailCreate protocol is designed to convert the results of docking
experiments into a database structure optimized for fast querying, filtering,
and analysis. It serves as the first step in post-processing large-scale
docking campaigns by importing the outputs generated by docking protocols and
storing them in a format compatible with the Ringtail back-end.

To use this protocol, the user must specify a folder that contains the output
files from a previous docking run. This folder should include docking logs,
pose files, and any associated metadata produced by protocols such as
AutoDock-GPU or AutoDock Vina. The protocol will scan the directory, identify
valid results, and organize them for ingestion.

The user must also choose the type of database to be generated. Ringtail
supports SQLite and other formats depending on the underlying configuration.
By default, an SQLite database is created in the output location, containing
the docking results in a structured schema that supports efficient filtering
by docking score, ligand name, binding site, and other criteria.

There is an option to specify a receptor file associated with the docking
results. When provided, this allows the database to record additional
information such as the target structure or the source of the interaction
grids. It also facilitates visualization and further processing.

The protocol offers parameters to control the verbosity of the import process
and to manage how errors or inconsistencies are handled. For instance, docking
files that are incomplete or improperly formatted can be skipped, logged, or
halt the process, depending on user preference.

Once executed, the protocol produces a database that serves as the foundation
for subsequent analysis steps using Ringtail tools. It enables integration with
filtering, rescoring, and selection protocols, offering a scalable way to manage
large virtual screening outputs within Scipion-Chem.

In summary, this protocol ingests raw docking outputs and transforms them into a
queryable database, ensuring reproducibility, traceability, and accessibility of
virtual screening results."""
  _label = 'Ringtail database creation'
  _program = ""

  def _defineParams(self, form):
    form.addSection(label='Input')
    group = form.addGroup('Input')
    group.addParam('inputSmallMolecules', params.PointerParam, pointerClass="SetOfSmallMolecules",
                   label='Input small molecules: ',
                   help="Input small molecules that will be processed by Ringtail")
    group.addParam('inOption', params.EnumParam, label='Molecules docked by: ', choices=inputOptions, default=0,
                   help='Define the origin of the input molecules')

  # --------------------------- INSERT steps functions --------------------
  def _insertAllSteps(self):
    self._insertFunctionStep('createOutputStep')

  def getDLGDir(self):
    molFile = self.inputSmallMolecules.get().getFirstItem().getPoseFile()
    molDir = os.path.dirname(molFile)
    return os.path.abspath(os.path.join('/'.join(os.path.split(molDir)[:-1]), 'extra'))

  def getSumPath(self):
    return self._getExtraPath('ringSum.txt')

  def createOutputStep(self):
    dlgDir = self.getDLGDir()
    args = f'write --file_path {dlgDir} --recursive -o ringtail.db '
    if self.inOption.get() == 1:
      args += '-m vina '
    autodockPlugin.runRingtail(self, args, cwd=self._getPath())

    outputDB = RingtailDatabase(filename=self._getPath('ringtail.db'))
    outputDB.createSumFile(self.getSumPath())
    self._defineOutputs(outputRingtail=outputDB)


  def _summary(self):
    s = []
    if os.path.exists(self.getSumPath()):
      with open(self.getSumPath()) as f:
        s.append(f.read())
    return s
