[PROTOCOLS]
Virtual Screening = [
	{"tag": "section", "text": "Library Filters", "openItem": "False", "children": [
	    {"tag": "protocol", "value": "ProtEncoderDockScoring",   "text": "default"}
	]},
    {"tag": "section", "text": "Pharmacophores", "openItem": "False", "children": [
        {"tag": "protocol", "value": "ProtChemAutoSiteGenPharmacophore",   "text": "default"}
    ]},
	{"tag": "section", "text": "Preparation", "icon": "bookmark.png", "children": [
	    {"tag": "protocol_group", "text": "Target Preparation", "openItem": "False", "children": [
	        {"tag": "protocol", "value": "ProtChemADTPrepareReceptor",   "text": "default"}
	    ]},
	    {"tag": "protocol_group", "text": "Ligand Preparation", "openItem": "False", "children": [
	        {"tag": "protocol", "value": "ProtChemADTPrepareLigands",   "text": "default"},
	        {"tag": "protocol", "value": "ProtScrubberPrepareLigands",   "text": "default"},
	        {"tag": "protocol", "value": "ProtChemMeekoLigands",   "text": "default"}
	    ]}
	]},
    {"tag": "section", "text": "Regions of interest", "children": [
        {"tag": "protocol_group", "text": "Pocket prediction", "openItem": "False", "children": [
            {"tag": "protocol", "value": "ProtChemAutoSite",   "text": "default"}
        ]},
        {"tag": "protocol_group", "text": "Grids generation", "openItem": "False", "children": [
            {"tag": "protocol", "value": "AutodockGridGeneration",   "text": "default"}
        ]}
    ]},
    {"tag": "section", "text": "Docking", "icon": "bookmark.png", "children": [
        {"tag": "protocol_group", "text": "Molecular Docking", "openItem": "False", "children": [
            {"tag": "protocol", "value": "ProtChemAutodock",   "text": "default"},
            {"tag": "protocol", "value": "ProtChemAutodockGPU",   "text": "default"},
            {"tag": "protocol", "value": "ProtChemVinaDocking",   "text": "default"},
            {"tag": "protocol", "value": "ProtChemVinaGPU",   "text": "default"}
        ]},
        {"tag": "protocol_group", "text": "Rescore Docking", "openItem": "False", "children": [
            {"tag": "protocol", "value": "ProtChemAutodockScore",   "text": "default"}
        ]},
        {"tag": "protocol_group", "text": "Protein-Protein Docking", "openItem": "False", "children": [
            {"tag": "protocol", "value": "ProtCrankPep",   "text": "default"}
        ]},
        {"tag": "protocol_group", "text": "RingTail database", "openItem": "False", "children": [
            {"tag": "protocol", "value": "ProtRingtailCreation",   "text": "default"},
            {"tag": "protocol", "value": "ProtRingtailFilter",   "text": "default"}
        ]}
	]}
    ]
