# Name of the GitHub Action
name: Build scipion-chem on Pull Request

# Specify when the Action should be triggered: when a pull request is opened against the 'devel' or 'master' branch
on:
  pull_request:
    branches: [devel, master]

# Define the job that should be run
jobs:
  build:
    # Specify the machine to run the job on
    runs-on: ubuntu-latest

    # Define the steps to be taken in the job
    steps:    
    # Installing wget, needed for downloading some dependencies
    - name: Install wget
      run: |
        # Update package lists and install wget
        sudo apt-get update && \
        sudo apt-get install -y wget
    
    # Installing Miniconda
    - name: Install Miniconda
      working-directory: ${{ github.workspace }}/../
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
        bash Miniconda3-latest-Linux-x86_64.sh -b -p ${{ github.workspace }}/../miniconda/ && \
        source ./miniconda/etc/profile.d/conda.sh
    
    # Installing Scipion
    - name: Install Scipion with dependencies
      working-directory: ${{ github.workspace }}/../
      run: |
        sudo apt-get install -y gcc-10 g++-10 libopenmpi-dev make && \
        eval "$(${{ github.workspace }}/../miniconda/bin/conda shell.bash hook)" && \
        pip3 install --user scipion-installer && \
        python3 -m scipioninstaller -conda -noXmipp -noAsk ${{ github.workspace }}/../scipion
      
    # Install scipion-chem
    - name: Install scipion-chem
      working-directory: ${{ github.workspace }}/../
      run: |
        git clone https://github.com/scipion-chem/scipion-chem.git && \
        scipion/scipion3 installp -p scipion-chem --devel
    
    # Check out the repository in the pull request
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    # Install plugin from the pull request using the Scipion3 installp command
    - name: Install plugin from pull request
      working-directory: ${{ github.workspace }}
      run: |
        # Install the repository from the pull request
        ../scipion/scipion3 installp -p . --devel
